### ISSUE TITLE
The difference between Var and VCAR

### ISSUE THREAD

**Issue by YanyanPop** [wzekai/FAT#1]
Hello, it is my pleasure to read your paper and I have some questions I would like to inquire about, if it is not too much trouble. 
First, I want to know the difference between Var and VCAR, and why not using Var as a regularization?
Second, about the proof of the Theorem 6.1, Jensen's inequality, as I know, is f(E(x)) <= E(f(x)), so I do not understand here.
I'm sorry to disturb you and I'm looking forward to your reply. Thanks

**Comment by shuxuexiaobai** [comment]
Var of the loss function is caused by the examples, which can be used to describe the disparity of average loss, instead of the disparity of class-wise loss.
